export const API_ERROR_CODES = [
  "ACCOUNT_PROVIDER_RESTRICTED",
  "CHANNEL_ALREADY_CONNECTED",
  "CHANNEL_LIMIT_REACHED",
  "CHANNEL_NOT_FOUND",
  "CHANNEL_PROVIDER_UNAVAILABLE",
  "CHANNEL_REAUTH_REQUIRED",
  "EMAIL_ALREADY_REGISTERED",
  "EMAIL_UNCHANGED",
  "INTERNAL_ERROR",
  "INVALID_CHALLENGE",
  "INVALID_CODE",
  "INVALID_CREDENTIALS",
  "INVALID_OAUTH_STATE",
  "INVALID_TIMEZONE",
  "MEDIA_IN_USE",
  "MEDIA_INVALID_TYPE",
  "MEDIA_NOT_FOUND",
  "MEDIA_NOT_READY",
  "MEDIA_SIZE_MISMATCH",
  "MEDIA_STORAGE_UNAVAILABLE",
  "MEDIA_UPLOAD_EXPIRED",
  "INVITATION_ALREADY_ACCEPTED",
  "INVITATION_DUPLICATE",
  "INVITATION_EMAIL_FAILED",
  "INVITATION_EMAIL_MISMATCH",
  "INVITATION_EXPIRED",
  "INVITATION_INVALID",
  "INVITATION_REVOKED",
  "NOT_READY",
  "ORIGIN_FORBIDDEN",
  "PASSWORD_UNCHANGED",
  "PUBLICATION_IMMUTABLE",
  "PUBLICATION_INVALID_STATUS",
  "PUBLICATION_NOT_FOUND",
  "PUBLICATION_TRIAL_LIMIT_REACHED",
  "RATE_LIMITED",
  "RESEND_COOLDOWN",
  "TAG_GROUP_NAME_CONFLICT",
  "TAG_GROUP_NOT_FOUND",
  "WORKSPACE_MEMBER_EXISTS",
  "WORKSPACE_MEMBER_LIMIT_REACHED",
  "WORKSPACE_MEMBER_NOT_FOUND",
  "UNAUTHENTICATED",
  "VALIDATION_ERROR",
  "WORKSPACE_FORBIDDEN",
  "WORKSPACE_NOT_FOUND",
] as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[number];

export interface ApiErrorDetail {
  field: string;
  code: string;
  params?: Record<string, string | number | boolean>;
}

export interface ApiError {
  statusCode: number;
  code: ApiErrorCode | `HTTP_${number}`;
  message: string;
  details?: ApiErrorDetail[];
}
