CREATE TYPE "IdentityProvider" AS ENUM ('password');
CREATE TYPE "ChallengePurpose" AS ENUM ('register', 'login', 'password_reset');
CREATE TYPE "WorkspaceRole" AS ENUM ('owner', 'admin', 'editor', 'viewer');
CREATE TYPE "SubscriptionStatus" AS ENUM ('trialing', 'active', 'past_due', 'canceled', 'expired');
CREATE TABLE "User" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "Identity" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "provider" "IdentityProvider" NOT NULL, "providerSubject" TEXT NOT NULL, "emailVerified" BOOLEAN NOT NULL DEFAULT false, CONSTRAINT "Identity_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE);
CREATE UNIQUE INDEX "Identity_provider_providerSubject_key" ON "Identity"("provider", "providerSubject");
CREATE UNIQUE INDEX "Identity_userId_provider_key" ON "Identity"("userId", "provider");
CREATE TABLE "PasswordCredential" ("identityId" TEXT PRIMARY KEY, "passwordHash" TEXT NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PasswordCredential_identityId_fkey" FOREIGN KEY ("identityId") REFERENCES "Identity"("id") ON DELETE CASCADE);
CREATE TABLE "EmailChallenge" ("id" TEXT PRIMARY KEY, "purpose" "ChallengePurpose" NOT NULL, "email" TEXT NOT NULL, "codeHash" TEXT NOT NULL, "attempts" INTEGER NOT NULL DEFAULT 0, "expiresAt" TIMESTAMP(3) NOT NULL, "consumedAt" TIMESTAMP(3), "lastSentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "pendingName" TEXT, "pendingPassword" TEXT, "pendingTimezone" TEXT, "userId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "EmailChallenge_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE);
CREATE INDEX "EmailChallenge_email_purpose_idx" ON "EmailChallenge"("email", "purpose");
CREATE TABLE "Session" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "tokenHash" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE);
CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash");
CREATE INDEX "Session_userId_idx" ON "Session"("userId");
CREATE TABLE "Workspace" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "ownerId" TEXT NOT NULL, "timezone" TEXT NOT NULL, "subscriptionStatus" "SubscriptionStatus" NOT NULL DEFAULT 'trialing', "subscriptionChannels" INTEGER NOT NULL DEFAULT 3, "subscriptionMembers" INTEGER NOT NULL DEFAULT 1, "trialStartedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "trialEndsAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Workspace_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT);
CREATE INDEX "Workspace_ownerId_idx" ON "Workspace"("ownerId");
CREATE TABLE "WorkspaceMember" ("workspaceId" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" "WorkspaceRole" NOT NULL, "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("workspaceId", "userId"), CONSTRAINT "WorkspaceMember_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE, CONSTRAINT "WorkspaceMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE);
CREATE INDEX "WorkspaceMember_userId_idx" ON "WorkspaceMember"("userId");
